"use client";

import { useCallback, useEffect, useState } from "react";
import {
  AlertTriangle,
  Award,
  ChevronDown,
  ChevronUp,
  FileText,
  Printer,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, THead, TBody, TR, TH, TD } from "@/components/ui/table";
import { cn } from "@/lib/utils";

// ─── Types ──────────────────────────────────────────────────────────

interface ReportCard {
  id: string;
  student: { id: string; name: string; guardianName: string; studentId: string | null };
  classSection: { id: string; className: string; sectionName: string };
  term: { id: string; name: string };
  generatedByTeacher: { id: string; name: string };
  createdAt: string;
  reportCardTests: {
    test: {
      id: string;
      title: string;
      date: string;
      maxMarks: number;
      subject: { name: string };
    };
  }[];
}

// ─── Component ──────────────────────────────────────────────────────

export function ReportCardOverview() {
  const [reportCards, setReportCards] = useState<ReportCard[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const loadReportCards = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/report-cards");
      if (!res.ok) throw new Error("Failed to load report cards");
      const json = await res.json();
      setReportCards(json.data ?? []);
    } catch {
      setError("Failed to load report cards.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadReportCards();
  }, [loadReportCards]);

  const toggleExpand = useCallback((id: string) => {
    setExpandedId((prev) => (prev === id ? null : id));
  }, []);

  return (
    <>
      <PageHeader
        title="Report Cards"
        description="View all generated report cards. Read-only oversight."
      />

      {loading ? (
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <Skeleton key={i} className="h-14 w-full" />
          ))}
        </div>
      ) : error ? (
        <EmptyState
          icon={AlertTriangle}
          title="Error loading report cards"
          description={error}
          action={
            <Button variant="secondary" onClick={loadReportCards}>
              Retry
            </Button>
          }
        />
      ) : reportCards.length === 0 ? (
        <EmptyState
          icon={Award}
          title="No report cards yet"
          description="Report cards generated by Class Teachers will appear here."
        />
      ) : (
        <div className="space-y-2">
          {reportCards.map((rc) => {
            const isExpanded = expandedId === rc.id;
            const totalMarks = rc.reportCardTests.reduce(
              (sum, rct) => sum + rct.test.maxMarks,
              0,
            );

            return (
              <Card key={rc.id} className="overflow-hidden">
                <button
                  type="button"
                  onClick={() => toggleExpand(rc.id)}
                  className="flex w-full items-center gap-4 px-4 py-3 text-left hover:bg-surface"
                  aria-expanded={isExpanded}
                >
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-xs tabular-nums text-text/50">{rc.student.studentId ?? ""}</span>
                      <span className="font-medium">{rc.student.name}</span>
                      <span className="text-xs text-text/40">•</span>
                      <span className="text-sm text-text/60">
                        {rc.classSection.className} — {rc.classSection.sectionName}
                      </span>
                    </div>
                    <div className="mt-0.5 text-xs text-text/50">
                      {rc.term.name} · {rc.reportCardTests.length} tests · Total max: {totalMarks} ·{" "}
                      Generated by {rc.generatedByTeacher.name}
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="ghost"
                      onClick={(e) => {
                        e.stopPropagation();
                        window.open(`/print/report-cards/${rc.id}`, "_blank");
                      }}
                      title="Print report card"
                    >
                      <Printer className="size-3.5" aria-hidden="true" />
                    </Button>
                    {isExpanded ? (
                      <ChevronUp className="size-4 text-text/40" />
                    ) : (
                      <ChevronDown className="size-4 text-text/40" />
                    )}
                  </div>
                </button>

                {isExpanded && (
                  <div className="border-t border-border px-4 py-3">
                    <h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text/50">
                      Tests Included
                    </h4>
                    <Table>
                      <THead>
                        <TR>
                          <TH>Subject</TH>
                          <TH>Test Title</TH>
                          <TH>Date</TH>
                          <TH className="text-center">Max Marks</TH>
                        </TR>
                      </THead>
                      <TBody>
                        {rc.reportCardTests.map((rct) => (
                          <TR key={rct.test.id}>
                            <TD>{rct.test.subject.name}</TD>
                            <TD className="font-medium">{rct.test.title}</TD>
                            <TD className="tabular-nums">{rct.test.date}</TD>
                            <TD className="text-center tabular-nums">{rct.test.maxMarks}</TD>
                          </TR>
                        ))}
                      </TBody>
                    </Table>
                  </div>
                )}
              </Card>
            );
          })}
        </div>
      )}
    </>
  );
}
