import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { ApiError, requireRole } from "@/lib/rbac";

/**
 * GET /api/teacher-attendance/export
 *
 * Admin only. Download teacher attendance records as CSV.
 *
 * Query params (all optional):
 *   - teacherId: filter to a specific teacher
 *   - from / to: date range (ISO date strings, inclusive)
 *
 * CSV includes school metadata header rows per §8 requirements.
 */
export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    requireRole(session, ["ADMIN"]);

    const { searchParams } = new URL(request.url);
    const teacherId = searchParams.get("teacherId");
    const from = searchParams.get("from");
    const to = searchParams.get("to");

    const where: Record<string, unknown> = {};
    if (teacherId) where.teacherId = teacherId;
    if (from || to) {
      where.date = {};
      if (from) (where.date as Record<string, Date>).gte = new Date(from);
      if (to) (where.date as Record<string, Date>).lte = new Date(to);
    }

    const records = await prisma.teacherAttendance.findMany({
      where,
      include: {
        teacher: {
          select: { id: true, name: true, phone: true },
        },
      },
      orderBy: [{ date: "desc" }, { createdAt: "desc" }],
    });

    // Get school settings for CSV metadata
    const schoolSettings = await prisma.schoolSettings.findFirst();

    // Get the current user's info for "Generated By"
    const user = await prisma.user.findUnique({
      where: { id: (session as any).user.id as string },
      select: { name: true, role: true },
    });

    // Build CSV
    const lines: string[] = [];

    // School metadata header rows (§8)
    if (schoolSettings) {
      if (schoolSettings.schoolName) lines.push(`School: ${schoolSettings.schoolName}`);
      if (schoolSettings.address) lines.push(`Address: ${schoolSettings.address}`);
      if (schoolSettings.phone) lines.push(`Phone: ${schoolSettings.phone}`);
    }
    if (user) {
      lines.push(`Generated By: ${user.name}`);
      lines.push(`Role: ${user.role}`);
    }
    lines.push(`Generated At: ${new Date().toISOString().replace("T", " ").slice(0, 19)}`);
    lines.push("");

    // Data header — includes new time-tracking columns
    lines.push("Teacher Name,Phone,Date,Status,Reporting Time,Off Time");

    // Data rows
    for (const record of records) {
      const name = escapeCsvField(record.teacher.name);
      const phone = escapeCsvField(record.teacher.phone);
      const date = new Date(record.date).toISOString().split("T")[0];
      const status = record.status;
      const reportingTime = record.actualReportingTime ?? "";
      const offTime = record.actualOffTime ?? "";
      lines.push(`${name},${phone},${date},${status},${reportingTime},${offTime}`);
    }

    const csv = lines.join("\n");

    return new NextResponse(csv, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="teacher-attendance-${new Date().toISOString().split("T")[0]}.csv"`,
      },
    });
  } catch (error) {
    if (error instanceof ApiError) {
      return NextResponse.json(
        { error: { message: error.message, code: error.code } },
        { status: error.status },
      );
    }
    console.error(error);
    return NextResponse.json(
      { error: { message: "An internal error occurred.", code: "INTERNAL_ERROR" } },
      { status: 500 },
    );
  }
}

/** Escape a string for CSV (wrap in quotes if it contains comma, quote, or newline). */
function escapeCsvField(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}
