import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { Award } from "lucide-react";
import { authOptions } from "@/lib/auth";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader } from "@/components/ui/page-header";

export const metadata: Metadata = {
  title: "Report Cards — Admin",
};

export default async function AdminReportCardsPage() {
  const session = await getServerSession(authOptions);
  if (!session?.user) redirect("/login");
  if (session.user.role !== "ADMIN") redirect("/login");

  return (
    <>
      <PageHeader
        title="Report Cards"
        description="View and manage generated report cards."
      />
      <EmptyState
        icon={Award}
        title="Report card oversight"
        description="Report cards are generated by Class Teachers. As Admin, you can view all generated report cards. A dedicated overview UI is planned."
      />
    </>
  );
}
